"""add durable ticket reservations

Revision ID: 8695b8a0c366
Revises: f6a7b8c90123
Create Date: 2026-09-21 07:10:46.576012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8695b8a0c366'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c90123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reservations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('tier_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'consumed', 'released')", name='ck_ticket_reservations_status'),
    sa.CheckConstraint('quantity > 0', name='ck_ticket_reservations_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_ticket_reservations_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['ticket_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'tier_id', name='uq_ticket_reservations_order_tier')
    )
    op.create_index(op.f('ix_ticket_reservations_order_id'), 'ticket_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_ticket_reservations_status'), 'ticket_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_reservations_tier_id'), 'ticket_reservations', ['tier_id'], unique=False)
    op.add_column('orders', sa.Column('subtotal_amount', sa.Float(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('checkout_attempt_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('orders', sa.Column('checkout_payload_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('orders', sa.Column('stripe_account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('orders', sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_orders_checkout_attempt_id'), 'orders', ['checkout_attempt_id'], unique=True)
    op.create_index(op.f('ix_orders_stripe_account_id'), 'orders', ['stripe_account_id'], unique=False)
    op.alter_column('orders', 'subtotal_amount', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_stripe_account_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_checkout_attempt_id'), table_name='orders')
    op.drop_column('orders', 'promo_code')
    op.drop_column('orders', 'stripe_account_id')
    op.drop_column('orders', 'checkout_payload_hash')
    op.drop_column('orders', 'checkout_attempt_id')
    op.drop_column('orders', 'subtotal_amount')
    op.drop_index(op.f('ix_ticket_reservations_tier_id'), table_name='ticket_reservations')
    op.drop_index(op.f('ix_ticket_reservations_status'), table_name='ticket_reservations')
    op.drop_index(op.f('ix_ticket_reservations_order_id'), table_name='ticket_reservations')
    op.drop_table('ticket_reservations')
    # ### end Alembic commands ###
