"""Add composite index for status and date_start

Revision ID: 869936c87afe
Revises: e40d1624dc85
Create Date: 2026-08-13 15:46:22.814433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869936c87afe'
down_revision: Union[str, Sequence[str], None] = 'e40d1624dc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_status_date_start', 'events', ['status', 'date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_date_start', table_name='events')
    # ### end Alembic commands ###
