"""add_native_ticketing_schema_and_tier_extensions

Revision ID: 9c316f37862e
Revises: 869936c87afe
Create Date: 2026-08-16 14:26:49.585419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c316f37862e'
down_revision: Union[str, Sequence[str], None] = '869936c87afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_stripe_accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_profile_id', sa.String(), nullable=False),
    sa.Column('stripe_account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_profile_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_stripe_accounts_organizer_profile_id'), 'organizer_stripe_accounts', ['organizer_profile_id'], unique=True)
    op.create_index(op.f('ix_organizer_stripe_accounts_stripe_account_id'), 'organizer_stripe_accounts', ['stripe_account_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_ref', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('buyer_user_id', sa.String(), nullable=True),
    sa.Column('buyer_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('buyer_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee_amount', sa.Float(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('attendee_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_email'), 'orders', ['buyer_email'], unique=False)
    op.create_index(op.f('ix_orders_buyer_user_id'), 'orders', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    op.create_index(op.f('ix_orders_order_ref'), 'orders', ['order_ref'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=True)
    op.create_table('ticket_tiers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('max_per_order', sa.Integer(), nullable=False),
    sa.Column('sale_start', sa.DateTime(), nullable=True),
    sa.Column('sale_end', sa.DateTime(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_tiers_event_id'), 'ticket_tiers', ['event_id'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('code_text', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('target_tier_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_tier_id'], ['ticket_tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code_text'), 'promo_codes', ['code_text'], unique=False)
    op.create_index(op.f('ix_promo_codes_event_id'), 'promo_codes', ['event_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('tier_id', sa.String(), nullable=False),
    sa.Column('qr_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['ticket_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_order_id'), 'tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_tickets_qr_token'), 'tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_tier_id'), 'tickets', ['tier_id'], unique=False)
    op.add_column('events', sa.Column('is_ticketing_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('sales_frozen', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('refund_cutoff_hours', sa.Integer(), server_default='48', nullable=False))
    op.add_column('events', sa.Column('ticket_support_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('events', sa.Column('scanner_access_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('events', sa.Column('checkout_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_scanner_access_key'), 'events', ['scanner_access_key'], unique=False)
    op.add_column('users', sa.Column('seller_tier', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('seller_status', sqlmodel.sql.sqltypes.AutoString(), server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seller_status')
    op.drop_column('users', 'seller_tier')
    op.drop_index(op.f('ix_events_scanner_access_key'), table_name='events')
    op.drop_column('events', 'checkout_questions')
    op.drop_column('events', 'scanner_access_key')
    op.drop_column('events', 'ticket_support_email')
    op.drop_column('events', 'refund_cutoff_hours')
    op.drop_column('events', 'sales_frozen')
    op.drop_column('events', 'is_ticketing_enabled')
    op.drop_index(op.f('ix_tickets_tier_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_qr_token'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_order_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_promo_codes_event_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code_text'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_ticket_tiers_event_id'), table_name='ticket_tiers')
    op.drop_table('ticket_tiers')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_ref'), table_name='orders')
    op.drop_index(op.f('ix_orders_event_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_organizer_stripe_accounts_stripe_account_id'), table_name='organizer_stripe_accounts')
    op.drop_index(op.f('ix_organizer_stripe_accounts_organizer_profile_id'), table_name='organizer_stripe_accounts')
    op.drop_table('organizer_stripe_accounts')
    # ### end Alembic commands ###
