"""Add collection hero custom fields

Revision ID: e40d1624dc85
Revises: ecae8676089f
Create Date: 2026-08-12 10:21:40.999553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e40d1624dc85'
down_revision: Union[str, Sequence[str], None] = 'ecae8676089f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('badge_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('external_link_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('collections', sa.Column('external_link_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_1_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_1_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_2_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_2_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_3_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('stat_3_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('collections', sa.Column('specific_venue_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'specific_venue_ids')
    op.drop_column('collections', 'stat_3_value')
    op.drop_column('collections', 'stat_3_label')
    op.drop_column('collections', 'stat_2_value')
    op.drop_column('collections', 'stat_2_label')
    op.drop_column('collections', 'stat_1_value')
    op.drop_column('collections', 'stat_1_label')
    op.drop_column('collections', 'external_link_label')
    op.drop_column('collections', 'external_link_url')
    op.drop_column('collections', 'badge_text')
    # ### end Alembic commands ###
