"""add_seller_tier_to_users

Revision ID: e9b6ba72632d
Revises: 9c316f37862e
Create Date: 2026-08-16 15:04:18.569994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b6ba72632d'
down_revision: Union[str, Sequence[str], None] = '9c316f37862e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_ticketing_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('events', sa.Column('sales_frozen', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('events', sa.Column('refund_cutoff_hours', sa.Integer(), nullable=False, server_default=sa.text('48')))
    op.add_column('events', sa.Column('ticket_support_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('events', sa.Column('scanner_access_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('events', sa.Column('checkout_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_events_scanner_access_key'), 'events', ['scanner_access_key'], unique=False)
    op.add_column('users', sa.Column('seller_tier', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.add_column('users', sa.Column('seller_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("'none'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seller_status')
    op.drop_column('users', 'seller_tier')
    op.drop_index(op.f('ix_events_scanner_access_key'), table_name='events')
    op.drop_column('events', 'checkout_questions')
    op.drop_column('events', 'scanner_access_key')
    op.drop_column('events', 'ticket_support_email')
    op.drop_column('events', 'refund_cutoff_hours')
    op.drop_column('events', 'sales_frozen')
    op.drop_column('events', 'is_ticketing_enabled')
    # ### end Alembic commands ###
