"""add recurrence_end_date to event

Revision ID: ecae8676089f
Revises: c6a141c8f560
Create Date: 2026-07-29 20:29:49.671381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecae8676089f'
down_revision: Union[str, Sequence[str], None] = 'c6a141c8f560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookmarks', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_user_event_bookmark', 'bookmarks', ['user_id', 'event_id'])
    op.drop_constraint(op.f('bookmarks_user_id_fkey'), 'bookmarks', type_='foreignkey')
    op.drop_constraint(op.f('bookmarks_event_id_fkey'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('collections', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('collections', 'show_on_map',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('event_attendees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('uq_event_attendee_user_event'), 'event_attendees', type_='unique')
    op.drop_constraint(op.f('fk_event_attendees_event'), 'event_attendees', type_='foreignkey')
    op.drop_constraint(op.f('fk_event_attendees_user'), 'event_attendees', type_='foreignkey')
    op.create_foreign_key(None, 'event_attendees', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event_attendees', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('event_participating_venues_event_id_fkey'), 'event_participating_venues', type_='foreignkey')
    op.create_foreign_key(None, 'event_participating_venues', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('event_tags_event_id_fkey'), 'event_tags', type_='foreignkey')
    op.create_foreign_key(None, 'event_tags', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('recurrence_end_date', sa.DateTime(), nullable=True))
    op.alter_column('events', 'seo_description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('events', 'min_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('events', 'organizer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'attending_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'save_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'ticket_click_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'website_click_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'is_all_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_events_title_trgm'), table_name='events', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_events_slug'), table_name='events', postgresql_where='(slug IS NOT NULL)')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=False)
    op.drop_constraint(op.f('events_category_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_organizer_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_venue_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_organizer_profile_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'organizers', ['organizer_profile_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('featured_bookings', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('featured_bookings', 'organizer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('featured_bookings_event_id_fkey'), 'featured_bookings', type_='foreignkey')
    op.drop_constraint(op.f('featured_bookings_organizer_id_fkey'), 'featured_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'featured_bookings', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'featured_bookings', 'users', ['organizer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizers', 'group_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('organizers', 'category_focus',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('organizers', 'upcoming_events_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('organizers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_organizers_city'), table_name='organizers')
    op.alter_column('promotions', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('promotions_venue_id_fkey'), 'promotions', type_='foreignkey')
    op.create_foreign_key(None, 'promotions', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('promotions', 'requires_checkin')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'is_trusted_organizer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('uq_user_username'), 'users', type_='unique')

    op.alter_column('venues', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('venues', 'seo_description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('venues', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_venues_slug'), table_name='venues', postgresql_where='(slug IS NOT NULL)')
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=False)
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_status'), 'venues', ['status'], unique=False)
    op.drop_constraint(op.f('venues_owner_id_fkey'), 'venues', type_='foreignkey')
    op.create_foreign_key(None, 'venues', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.create_foreign_key(op.f('venues_owner_id_fkey'), 'venues', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_venues_status'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_index(op.f('ix_venues_slug'), table_name='venues')
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=True, postgresql_where='(slug IS NOT NULL)')
    op.alter_column('venues', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('venues', 'seo_description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('venues', 'status',
               existing_type=sa.Enum('VERIFIED', 'UNVERIFIED', 'ARCHIVED', name='venuestatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.create_unique_constraint(op.f('uq_user_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_trusted_organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('promotions', sa.Column('requires_checkin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.create_foreign_key(op.f('promotions_venue_id_fkey'), 'promotions', 'venues', ['venue_id'], ['id'])
    op.alter_column('promotions', 'venue_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_organizers_city'), 'organizers', ['city'], unique=False)
    op.alter_column('organizers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('organizers', 'upcoming_events_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('organizers', 'category_focus',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('organizers', 'group_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'featured_bookings', type_='foreignkey')
    op.drop_constraint(None, 'featured_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('featured_bookings_organizer_id_fkey'), 'featured_bookings', 'users', ['organizer_id'], ['id'])
    op.create_foreign_key(op.f('featured_bookings_event_id_fkey'), 'featured_bookings', 'events', ['event_id'], ['id'])
    op.alter_column('featured_bookings', 'organizer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('featured_bookings', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_organizer_profile_id_fkey'), 'events', 'organizers', ['organizer_profile_id'], ['id'])
    op.create_foreign_key(op.f('events_venue_id_fkey'), 'events', 'venues', ['venue_id'], ['id'])
    op.create_foreign_key(op.f('events_organizer_id_fkey'), 'events', 'users', ['organizer_id'], ['id'])
    op.create_foreign_key(op.f('events_category_id_fkey'), 'events', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True, postgresql_where='(slug IS NOT NULL)')
    op.create_index(op.f('idx_events_title_trgm'), 'events', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('events', 'is_all_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'website_click_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'ticket_click_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'save_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'attending_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('events', 'organizer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'min_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('events', 'seo_description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('events', 'recurrence_end_date')
    op.drop_constraint(None, 'event_tags', type_='foreignkey')
    op.create_foreign_key(op.f('event_tags_event_id_fkey'), 'event_tags', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'event_participating_venues', type_='foreignkey')
    op.create_foreign_key(op.f('event_participating_venues_event_id_fkey'), 'event_participating_venues', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'event_attendees', type_='foreignkey')
    op.drop_constraint(None, 'event_attendees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_attendees_user'), 'event_attendees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_event_attendees_event'), 'event_attendees', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_event_attendee_user_event'), 'event_attendees', ['user_id', 'event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('event_attendees', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('collections', 'show_on_map',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('collections', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('bookmarks_event_id_fkey'), 'bookmarks', 'events', ['event_id'], ['id'])
    op.create_foreign_key(op.f('bookmarks_user_id_fkey'), 'bookmarks', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_event_bookmark', 'bookmarks', type_='unique')
    op.alter_column('bookmarks', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
